const escape = (value) =>
  String(value ?? '').replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
  );
export function deliveryHtml(result, images, lang = 'en') {
  const t = (en, zh) => (lang === 'zh' ? zh : en);
  return `<!doctype html><html lang="${lang}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>ShipLens · ${t('Delivery proof', '保存验收')}</title><style>
:root{color-scheme:light dark;font-family:system-ui,sans-serif;color:#182c47;background:#f4f7fb;--paper:#fff;--muted:#526981;--line:#dce4ef;--accent:#234eb0}*{box-sizing:border-box}body{margin:0}header{padding:20px 24px;border-bottom:1px solid var(--line);background:var(--paper);font-weight:700}main{max-width:1000px;margin:40px auto;padding:0 24px}h1{font-size:clamp(28px,5vw,40px);letter-spacing:-.025em;line-height:1.15}h2{margin:36px 0 16px;font-size:23px}p{line-height:1.65;max-width:72ch;overflow-wrap:anywhere}.muted{color:var(--muted)}section{padding:24px 0;border-bottom:1px solid var(--line)}strong{font-size:20px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--paper);padding:16px;border:1px solid var(--line);font-size:13px;line-height:1.6}figure{margin:20px 0}.capture{overflow:auto;max-height:380px;border:1px solid var(--line);background:var(--paper)}img{display:block;max-width:none}figcaption{margin-top:8px;font-size:13px;color:var(--muted);line-height:1.5}summary{cursor:pointer;padding:12px 0;font-weight:600}summary:focus-visible,.capture:focus-visible{outline:2px solid var(--accent);outline-offset:4px}::selection{background:#d5e2ff;color:#172b4a}@media(prefers-color-scheme:dark){:root{color:#e3edf7;background:#101923;--paper:#172331;--muted:#abbdd0;--line:#35465b;--accent:#b1c8ff}}@media(max-width:640px){main{margin:28px auto;padding:0 18px}}
</style><header>ShipLens</header><main><h1>${t('Delivery proof', '保存验收')}</h1><p>${escape(result.name)}</p><strong>${result.passed ? t('Contract passed', '配置的保存契约通过') : t('Contract requires attention', '保存契约仍需处理')}</strong><p>${t('The browser action, independent server readback and injected failure are checked separately.', '分别检查浏览器操作、独立接口读取和主动注入的失败。')}</p><p class="muted">${escape(result.deliveryId)}</p>${result.trials.map((trial) => `<section><h2>${escape(trial.viewport)} · ${trial.phase === 'success' ? t('Real save', '真实保存') : t('Injected HTTP 503', '注入 HTTP 503')}</h2><p>${escape(trial.status)}${trial.reasons.length ? ' · ' + escape(trial.reasons.join(' · ')) : ''}</p>${trial.before && trial.after ? `<p>${t('Matching records before / after', '匹配记录：操作前 / 后')}: ${escape(trial.before.count)} / ${escape(trial.after.count ?? t('unavailable', '不可用'))}</p>` : ''}${trial.evidence ? `<figure><div class="capture" tabindex="0" role="region" aria-label="${t('Captured component', '组件截图')}"><img src="data:image/png;base64,${images[trial.evidence.image]}" alt="${escape(trial.viewport + ' · ' + trial.phase)}"></div><figcaption>${t('Captured component · scroll to inspect at original size', '组件截图 · 可滚动查看原始尺寸')}</figcaption></figure>` : ''}<details><summary>${t('Request, readback and UI evidence', '请求、接口读取与页面证据')}</summary><pre>${escape(JSON.stringify(trial, null, 2))}</pre></details></section>`).join('')}<h2>${t('Scope and limits', '范围与边界')}</h2><p>${t('Success trials can create real test records; no automatic cleanup is performed. Readback checks the configured API projection, not database durability. Failure trials intercept the browser request with HTTP 503. This report does not certify unrelated pages, permissions or business rules.', '成功分支可能创建真实测试记录，不执行自动删除。独立读取检查配置的 API 返回内容，不证明数据库的持久化保证。失败分支将浏览器请求拦截为 HTTP 503。此报告不认证其他页面、权限或业务规则。')}</p><p class="muted">${escape(result.createdAt)} · v${escape(result.version)}</p></main></html>`;
}
